#!/bin/bash

set -eux

# Bring in the shared functions and variables
. /opt/bin/bootstrap.sh

reset_sentinel () {
  set +e
  timeout 10 redis-cli -h "$1" -p 26379 sentinel reset primaryserver
  set -e
}

find_master () {
  # It's okay to fail during failover or other unpredictable states.
  # This prevents from making things much worse.

  local servers
  servers="$(server_domains "$service_domain")"
  readonly servers

  local master_ip=''

  local s
  for s in $servers; do
    local s_ip
    s_ip="$(domain_ip "$s")"

    if [ -z "$s_ip" ]; then
      >&2 echo "Failed to resolve: $s"
      continue
    fi

    local i
    i="$(redis_info "$s_ip")"
    if [ -n "$i" ]; then
      if [ "$(redis_info_role "$i")" = 'master' ]; then
        master_ip="$s_ip"
      fi
    else
      >&2 echo "Unable to get Replication INFO: $s ($s_ip)"
      continue
    fi
  done

  echo ${master_ip}

}

counter=120
until [ $counter -le 0 ]
do
  master=$(find_master)
  if [ -z "${master}" ]
  then
    let counter-=1
    echo "$(date) Waiting for master..."
    sleep 5
  else
    break
  fi
done

< /opt/sentinel.template.conf sed "s/%MASTER%/$master/g" | \
  sed "s/%PASSWORD%/$REDIS_PASSWORD/g" > /opt/sentinel.conf

reset_all_sentinels
exec docker-entrypoint.sh redis-sentinel "$@"
