---
groups:
- name: all
  jobs:
  - elasticsearch-23
  - elasticsearch-17

jobs:
- name: elasticsearch-23
  plan:
  - get: kubernetes-broker
    trigger: true
  - put: docker-hub-elasticsearch-23
    params:
      build: kubernetes-broker/custom_images/docker-elasticsearch-kubernetes-auth-23

- name: elasticsearch-17
  plan:
  - get: kubernetes-broker
    trigger: true
  - put: docker-hub-elasticsearch-17
    params:
      build: kubernetes-broker/custom_images/docker-elasticsearch-kubernetes-auth-17

resources:
- name: kubernetes-broker
  type: git
  source:
    uri: {{kubernetes-broker-git-url}}
    branch: {{kubernetes-broker-git-branch}}
    paths:
    - custom_images/docker-elasticsearch-kubernetes-auth-*/*

- name: docker-hub-elasticsearch-23
  type: docker-image
  source:
    email: {{docker-email}}
    username: {{docker-username}}
    password: {{docker-password}}
    repository: {{docker-repo}}
    tag: {{docker-tag-elasticsearch-23}}

- name: docker-hub-elasticsearch-17
  type: docker-image
  source:
    email: {{docker-email}}
    username: {{docker-username}}
    password: {{docker-password}}
    repository: {{docker-repo}}
    tag: {{docker-tag-elasticsearch-17}}
